version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::873102235883:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-15MJNEPO111JW"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::873102235883:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1BZ0FKI54CHJS"
cloudformation_execution_role = "arn:aws:iam::873102235883:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-11V9XWH0REEJY"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1o1zu57ix6voz"
image_repository = ""
region = "ap-south-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::873102235883:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-17TA8BON3J5TL"
cloudformation_execution_role = "arn:aws:iam::873102235883:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-4ELX81KWLFDR"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-2s54z0yc7620"
image_repository = ""
region = "ap-south-1"
